// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isbxqaqhazscbifmevyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzYnhxYXFoYXpzY2JpZm1ldnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MzA0MTAsImV4cCI6MjA1NTQwNjQxMH0.v37avOYxA3TM7WvNqUmAs7LWGud0iQ9DzY-k6j-bkGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);